[build-system]
requires = ["setuptools", "torch"]
build-backend = "setuptools.build_meta"

[project]
name="monotonic_align"
dynamic = ["version"]

[tool.setuptools.packages.find]
include = [
    "monotonic_align",
]

[tool.setuptools.dynamic]
version = {attr = "monotonic_align.__version__"}
